[package]
name = "metrics_panic"
version = "0.1.0"
authors = ["Robert Masen <robert.masen@smartthings.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
metrics-runtime = "0.13"
metrics = "0.12"
rand = "0.7"
